### ISSUE TITLE
停止服务后点击启动服务异常崩溃

### ISSUE THREAD

**Issue by AndersJet** [wangshihu123/DaemonLibrary#3]
测试手机：海信F23
异常日志：
2019-03-05 16:17:14.594 22199-22199/com.shihoo.daemonlibrary:work E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shihoo.daemonlibrary:work, PID: 22199
    java.lang.RuntimeException: Unable to start service com.shihoo.daemonlibrary.MainWorkService@369dec2 with Intent { cmp=com.shihoo.daemonlibrary/.MainWorkService }: java.lang.IllegalArgumentException: Service not registered: com.shihoo.daemon.AbsWorkService$1@50d2810
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3357)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6166)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.shihoo.daemon.AbsWorkService$1@50d2810
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1499)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
        at com.shihoo.daemon.AbsWorkService.stopService(AbsWorkService.java:180)
        at com.shihoo.daemon.AbsWorkService.onStart(AbsWorkService.java:144)
        at com.shihoo.daemon.AbsWorkService.onStartCommand(AbsWorkService.java:69)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3340)
        at android.app.ActivityThread.-wrap21(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6166) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ShihooWang** [comment]
感谢您的反馈，该问题已修复。同学你可以：
1.如果你下载了源码，请注释掉 AbsWorkService类的144行-
   // 此处不比重复关闭服务。否则mConnection.mConnectedState的状态没有来得及改变，
   //  再次unbindService(conn)服务会导致 Service not registered 异常抛出。 服务启动和关闭都需要耗
   //时短时间内不宜频繁开启和关闭。
   // stopService(intent, flags, startId); 
2.或者使用 implementation 'com.github.wangshihu123:DaemonLibrary:v0.04'

**Comment by AndersJet** [comment]
好的，也非常感谢您。
